on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
      GMAIL_TUP: ${{ secrets.GMAIL_TUP }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    - name: Install Dependencies
      run: |
        # Navega al directorio 'tup'
        cd tup
        
        # Crea y activa un entorno virtual
        python -m venv venv
        . venv/bin/activate
        
        # Actualiza pip y instala las dependencias
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      run: |
        # Navega al directorio 'tup'
        cd tup
        
        # Activa el entorno virtual para esta sesión
        . venv/bin/activate
        
        # Ejecuta los tests
        pytest -v